// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// QcFile is the golang structure of table qc_file for DAO operations like Where/Data.
type QcFile struct {
	g.Meta   `orm:"table:qc_file, do:true"`
	Id       interface{} //
	Filename interface{} //
	Path     interface{} //
	Status   interface{} //
	CreateAt *gtime.Time //
	UpdateAt *gtime.Time //
	DeleteAt *gtime.Time //
}
