// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAiLink(arg1) {
  return window['go']['logic']['AiLinkLogic']['DeleteAiLink'](arg1);
}

export function GetAiLinkList() {
  return window['go']['logic']['AiLinkLogic']['GetAiLinkList']();
}

export function SaveAiLink(arg1) {
  return window['go']['logic']['AiLinkLogic']['SaveAiLink'](arg1);
}

export function UpdateAiLink(arg1) {
  return window['go']['logic']['AiLinkLogic']['UpdateAiLink'](arg1);
}
