// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tables} from '../models';

export function DeleteAiLink(arg1:tables.AiLink):Promise<void>;

export function GetAiLinkList():Promise<Array<tables.AiLink>>;

export function SaveAiLink(arg1:tables.AiLink):Promise<void>;

export function UpdateAiLink(arg1:tables.AiLink):Promise<void>;
