// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logic} from '../models';

export function AddFile():Promise<void>;

export function EditFile():Promise<void>;

export function GetFiles():Promise<Array<logic.QuickCmdFile>>;

export function Greet(arg1:string):Promise<string>;

export function RemoveFile():Promise<void>;

export function ToggleFile():Promise<void>;

export function ViewFile():Promise<void>;
