// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFile() {
  return window['go']['logic']['App']['AddFile']();
}

export function EditFile() {
  return window['go']['logic']['App']['EditFile']();
}

export function GetFiles() {
  return window['go']['logic']['App']['GetFiles']();
}

export function Greet(arg1) {
  return window['go']['logic']['App']['Greet'](arg1);
}

export function RemoveFile() {
  return window['go']['logic']['App']['RemoveFile']();
}

export function ToggleFile() {
  return window['go']['logic']['App']['ToggleFile']();
}

export function ViewFile() {
  return window['go']['logic']['App']['ViewFile']();
}
