// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"changeme/internal/dao/internal"
)

// internalQcFileDao is internal type for wrapping internal DAO implements.
type internalQcFileDao = *internal.QcFileDao

// qcFileDao is the data access object for table qc_file.
// You can define custom methods on it to extend its functionality as you wish.
type qcFileDao struct {
	internalQcFileDao
}

var (
	// QcFile is globally public accessible object for table qc_file operations.
	QcFile = qcFileDao{
		internal.NewQcFileDao(),
	}
)

// Fill with you ideas below.
