// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHost() {
  return window['go']['main']['App']['AddHost']();
}

export function EditHost() {
  return window['go']['main']['App']['EditHost']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RemoveHost() {
  return window['go']['main']['App']['RemoveHost']();
}

export function ToggleHost() {
  return window['go']['main']['App']['ToggleHost']();
}

export function ViewHost() {
  return window['go']['main']['App']['ViewHost']();
}
