// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHost():Promise<void>;

export function EditHost():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function RemoveHost():Promise<void>;

export function ToggleHost():Promise<void>;

export function ViewHost():Promise<void>;
