// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanBin() {
  return window['go']['main']['Recycle']['CleanBin']();
}

export function CleanFileFromBin(arg1) {
  return window['go']['main']['Recycle']['CleanFileFromBin'](arg1);
}

export function GetRecycleList() {
  return window['go']['main']['Recycle']['GetRecycleList']();
}

export function RestoreFileFromBin(arg1) {
  return window['go']['main']['Recycle']['RestoreFileFromBin'](arg1);
}
