// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tables} from '../models';

export function CleanBin():Promise<string>;

export function CleanFileFromBin(arg1:tables.Qc):Promise<string>;

export function GetRecycleList():Promise<Array<tables.Qc>>;

export function RestoreFileFromBin(arg1:tables.Qc):Promise<string>;
