# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Waild
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest 

    - name: Build darwin/amd64
      run: wails build -platform darwin/amd64 -clean && tar czvf SwitchQC-drawin-amd64-x.0.x.tar.gz build/bin/SwitchQC.app
 
    - name: Test
      run: ls
